services:
  # --- API Gateway (NGINX) ---
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
    networks:
      - backend-net

  auth:
    build:
      context: ./../autenticacion_servicio
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8082:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=ignacio_ad
      - QUARKUS_DATASOURCE_PASSWORD=1234
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/autenticacionBD
    depends_on:
      - postgres
    networks:
      - backend-net

  carrito_servicio:
    build:
      context: ./../carrito_servicio
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8083:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=ignacio_ad
      - QUARKUS_DATASOURCE_PASSWORD=1234
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/carritoBD
    depends_on:
      - postgres
    networks:
      - backend-net

  catalogo_servicio:
    build:
      context: ./../catalogo_servicio
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8084:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=ignacio_ad
      - QUARKUS_DATASOURCE_PASSWORD=1234
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/catalogoBD
    depends_on:
      - postgres
    networks:
      - backend-net

  pedido_servicio:
    build:
      context: ./../pedido_servicio
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8085:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=ignacio_ad
      - QUARKUS_DATASOURCE_PASSWORD=1234
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/pedidoBD
    depends_on:
      - postgres
    networks:
      - backend-net

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ignacio_ad
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - backend-net
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - backend-net

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    ports:
      - "19092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
