apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: autenticacion_servicio_quarkus:v2
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 130
            periodSeconds: 10
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "ignacio_ad"
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: "1234"
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://postgres-auth:5432/autenticacionBD"
