apiVersion: v1
kind: Service
metadata:
  name: autenticacion
  labels:
    app: autenticacion
spec:
  selector:
    app: autenticacion-microservicio
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP