apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrito-microservicio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carrito-microservicio
  template:
    metadata:
      labels:
        app: carrito-microservicio
    spec:
      containers:
        - name: carrito-microservicio
          image: carrito_servicio_quarkus:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "600Mi"
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "ignacio_ad"
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: "1234"
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://postgres-carrito:5432/carritoBD"
            - name: KAFKA_URL
              value: "kafka-service:9092"
            - name: CATALOGO_URL
              value: "http://catalogo:8080/catalogo"
            - name: QUARKUS_PROFILE
              value: "docker"
            - name: STRIPE_SECRET
              value: "sk_test_51RTK0006qtBCiEnjgcPndANKSxzyw1fCdIhzhQBNxiBWlAdjsWjoD4wmPbHcqmFDD5vTTDxvnvrNAtgQidkVuE6i00C0QR7j9h"
            - name: STRIPE_WEBHOOK_SECRET
              value: "whsec_a7f7416e7ce0902e5f3cbd891a948860c3444d25670202f365128c2577002fed"
            - name: AUTH_ADMIN_USER
              value: "idl00005@red.ujaen.es"
            - name: AUTH_ADMIN_PASSWORD
              value: "1234"
            - name: CACHE_REDIS_HOSTS
              value: "redis://redis:6379"