apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogo-microservicio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogo-microservicio
  template:
    metadata:
      labels:
        app: catalogo-microservicio
    spec:
      containers:
        - name: catalogo-microservicio
          image: catalogo_servicio_quarkus:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "600Mi"
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "ignacio_ad"
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: "1234"
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://postgres-catalogo:5432/catalogoBD"
            - name: KAFKA_URL
              value: "kafka-service:9092"
            - name: QUARKUS_PROFILE
              value: "docker"
            - name: CACHE_REDIS_HOSTS
              value: "redis://redis:6379"
  