apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogo-microservicio
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 180
  