apiVersion: v1
kind: Service
metadata:
  name: catalogo
  labels:
    app: catalogo
spec:
  selector:
    app: catalogo-microservicio
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
  