apiVersion: v1
kind: Service
metadata:
  name: pedido
  labels:
    app: pedido
spec:
  selector:
    app: pedido-microservicio
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
  