apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedido-servicio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pedido-servicio
  template:
    metadata:
      labels:
        app: pedido-servicio
    spec:
      containers:
        - name: pedido-servicio
          image: pedido_servicio_quarkus:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 115
            periodSeconds: 15
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 135
            periodSeconds: 3
            failureThreshold: 3
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "ignacio_ad"
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: "1234"
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://postgres-pedido:5432/pedidoBD"
            - name: CATALOGO_URL
              value: "http://catalogo-servicio:8080/catalogo"
            - name: KAFKA_URL
              value: "kafka-service:9092"
            - name: QUARKUS_PROFILE
              value: "docker"
            - name: CACHE_REDIS_HOSTS
              value: "redis://redis:6379"