apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-metrics
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: auth
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /q/metrics
      interval: 15s
  