{
 "title": "Consumo de recursos de los pods",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage per pod (default)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"default\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage per pod (default)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"default\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"default\"} / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage per pod (kube-system)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"kube-system\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage per pod (kube-system)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"kube-system\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"default\"} / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage per pod (monitoring)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"monitoring\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage per pod (monitoring)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"monitoring\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"default\"} / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}