{
 "title": "Monitorización de los microservicios",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage de los microservicios",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (label_replace(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[$__rate_interval]), \"pod\", \"$1\", \"pod\", \"^(.*)-[^-]+-[^-]+$\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instancias de los microservicios",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{namespace=\"default\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Memory usage de los microservicios",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by(deployment) (label_replace(container_memory_usage_bytes{namespace=\"default\"}, \"deployment\", \"$1\", \"pod\", \"^(.*)-[0-9a-z]+$\")) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia de las peticiones Total (Microservicio de Autenticación)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "avg(avg_over_time(application_com_Recursos_AutenticacionResource_checksTimer_mean_seconds[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latencia de las peticiones (Microservicio de Autenticación)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "avg_over_time(application_com_Recursos_AutenticacionResource_checksTimer_mean_seconds[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latencia de las peticiones Total (Microservicio de Carrito)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg(avg_over_time(application_Recursos_CarritoResource_checksTimer_mean_seconds[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latencia de las peticiones (Microservicio de Carrito)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "avg_over_time(application_Recursos_CarritoResource_checksTimer_mean_seconds[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latencia de las peticiones Total (Microservicio de Catálogo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "avg(avg_over_time(application_com_Recursos_CatalogoResource_checksTimer_mean_seconds[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latencia de las peticiones (Microservicio de Catálogo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "avg_over_time(application_com_Recursos_CatalogoResource_checksTimer_mean_seconds[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latencia de las peticiones Total (Microservicio de Pedidos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "avg(avg_over_time(application_Recursos_PedidoResource_checksTimer_mean_seconds[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latencia de las peticiones (Microservicio de Pedidos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "avg_over_time(application_Recursos_PedidoResource_checksTimer_mean_seconds[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de peticiones Total (Microservicio de Autenticacion)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(avg_over_time(application_com_Recursos_AutenticacionResource_performedChecks_total[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de peticiones (Microservicio de Autenticacion)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "avg_over_time(application_com_Recursos_AutenticacionResource_performedChecks_total[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de peticiones Total (Microservicio de Carrito)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(avg_over_time(application_Recursos_CarritoResource_performedChecks_total[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de peticiones (Microservicio de Carrito)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "avg_over_time(application_Recursos_CarritoResource_performedChecks_total[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de peticiones Total (Microservicio de Pedido)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(avg_over_time(application_Recursos_PedidoResource_performedChecks_total[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de peticiones (Microservicio de Pedido)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "avg_over_time(application_Recursos_PedidoResource_performedChecks_total[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de peticiones Total (Microservicio de Catalogo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum(avg_over_time(application_com_Recursos_CatalogoResource_performedChecks_total[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de peticiones (Microservicio de Catalogo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "avg_over_time(application_com_Recursos_CatalogoResource_performedChecks_total[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de errores/min Total (Microservicio de Autenticacion)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum(rate(application_Aplication_AutenticacionResource_primality_errors_total[1m])) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de errores/min (Microservicio de Autenticacion)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "rate(application_Aplication_AutenticacionResource_primality_errors_total[1m]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de errores/min Total (Microservicio de Carrito)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(rate(application_Aplication_CarritoResource_primality_errors_total[1m])) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de errores/min (Microservicio de Carrito)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "rate(application_Aplication_CarritoResource_primality_errors_total[1m]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de errores/min Total (Microservicio de Catálogo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sum(rate(application_Aplication_CatalogoResource_primality_errors_total[1m])) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de errores/min (Microservicio de Catálogo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "rate(application_Aplication_CatalogoResource_primality_errors_total[1m]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de errores/min Total (Microservicio de Pedido)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "sum(rate(application_Aplication_PedidoResource_primality_errors_total[1m])) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Número de errores/min (Microservicio de Pedido)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "rate(application_Aplication_PedidoResource_primality_errors_total[1m]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}