apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.js: |
    window.APP_CONFIG = {
        API_CARRITO: "/carrito",
        API_CATALOGO: "/catalogo",
        API_PEDIDOS: "/pedidos",
        API_AUTENTICACION: "/autenticacion"
    };
  