apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrito-servicio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: carrito-servicio
  template:
    metadata:
      labels:
        app: carrito-servicio
    spec:
      containers:
        - name: carrito-servicio
          image: carrito_servicio_quarkus:v1.2
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "ignacio_ad"
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: "1234"
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://postgres-carrito:5432/carritoBD"
            - name: KAFKA_URL
              value: "kafka-service:9092"
            - name: CATALOGO_URL
              value: "http://catalogo-servicio:8080"
            - name: QUARKUS_PROFILE
              value: "docker"